/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "inverse-surface": "#dde4e0",
        "primary-container": "#5ffbd6",
        "primary": "#ffffff",
        "primary-fixed-dim": "#38debb",
        "primary-fixed": "#5ffbd6",
        "surface-container-lowest": "#09100d",
        "surface-container-highest": "#2f3633",
        "error-container": "#93000a",
        "surface-variant": "#2f3633",
        "on-secondary": "#263049",
        "background": "#0e1512",
        "surface-container-high": "#242c29",
        "tertiary-fixed": "#fbe273",
        "secondary-container": "#3c4661",
        "on-background": "#dde4e0",
        "tertiary": "#ffffff",
        "secondary": "#bcc6e6",
        "on-tertiary-fixed-variant": "#534600",
        "surface-bright": "#333b38",
        "on-primary": "#00382d",
        "surface-container": "#1a211f",
        "surface": "#0e1512",
        "outline-variant": "#3c4a45",
        "error": "#ffb4ab",
        "on-secondary-fixed-variant": "#3c4661",
        "tertiary-fixed-dim": "#dec65a",
        "tertiary-container": "#fbe273",
        "on-primary-fixed-variant": "#005142",
        "on-secondary-fixed": "#101b33",
        "surface-tint": "#38debb",
        "secondary-fixed": "#d9e2ff",
        "on-surface-variant": "#bacac3",
        "outline": "#85948e",
        "on-tertiary-fixed": "#211b00",
        "on-secondary-container": "#aab4d4",
        "surface-container-low": "#161d1b",
        "on-tertiary": "#393000",
        "secondary-fixed-dim": "#bcc6e6",
        "on-error": "#690005",
        "inverse-on-surface": "#2b322f",
        "surface-dim": "#0e1512",
        "on-tertiary-container": "#756400",
        "on-surface": "#dde4e0",
        "on-primary-container": "#00725e",
        "inverse-primary": "#006b58",
        "on-primary-fixed": "#002019",
        "on-error-container": "#ffdad6"
      },
      borderRadius: {
        "DEFAULT": "8px",
        "lg": "12px",
        "xl": "16px",
        "2xl": "24px",
        "full": "9999px"
      },
      spacing: {
        "md": "24px",
        "container-max": "1280px",
        "lg": "48px",
        "base": "8px",
        "xl": "80px",
        "sm": "12px",
        "gutter": "24px",
        "xs": "4px"
      },
      fontFamily: {
        "body-sm": ["'Plus Jakarta Sans'", "sans-serif"],
        "headline-lg": ["Outfit", "sans-serif"],
        "display-xl-mobile": ["Outfit", "sans-serif"],
        "headline-md": ["Outfit", "sans-serif"],
        "body-md": ["'Plus Jakarta Sans'", "sans-serif"],
        "body-lg": ["'Plus Jakarta Sans'", "sans-serif"],
        "label-caps": ["'JetBrains Mono'", "monospace"],
        "display-xl": ["Outfit", "sans-serif"]
      },
      fontSize: {
        "body-sm": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
        "headline-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "700" }],
        "display-xl-mobile": ["40px", { "lineHeight": "48px", "letterSpacing": "-0.03em", "fontWeight": "800" }],
        "headline-md": ["24px", { "lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "700" }],
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "450" }],
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "450" }],
        "label-caps": ["12px", { "lineHeight": "16px", "letterSpacing": "0.1em", "fontWeight": "600" }],
        "display-xl": ["64px", { "lineHeight": "72px", "letterSpacing": "-0.04em", "fontWeight": "800" }]
      }
    }
  },
  plugins: [],
}
